Dockerfile
README.md
action.yml
review.py

- Replace absolute paths in `compile_commands.json` if it exists
- Needed due to container-based Actions being mounted in a different location, and `clang-tidy` not accepting relative paths
- Add argument to install additional apt packages
- Needed to bring in headers for third-party dependencies
- Fix for PRs with multiple files
- Fix for whitespace in code-blocks in comments

Various fixes, plus install additional apt packages

---

README.md
action.yml
review.py

It seems GitHub will only let you post so many review comments at once. I'm not sure of the exact number, so I've made it an input parameter. Could do something like post `n` at a time, looping till they're all done, but I figure posting 100 comments is a bit spammy anyway. Triggering another run of this action will post the next `max_comments` comments, so that's a nice compromise at least

Fix issue with creating a review with too many comments

---

Dockerfile

Fixes `WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

Avoid apt warning when building

---

review.py

The problem I was having with your Action was related to the compile_commands.json "directory" entry you make use of on line 350.  I'm guessing that you assumed that the directory is always terminated with a /.  In my case it is not.  This leads to an error later when replacing that directory path which does not exist.  I noticed other people saw the same thing, so I'm proposing this simple change to check that you're really removing a /.  Works for me now.

#20 - Fix path replace problem

---

Dockerfile
README.md
action.yml
review.py

Closes #22 
~Possibly fix for #14~
By running the CMake command inside the container when the Action is run, we can avoid having to faff about trying to fix the paths in `compile_commands.json`.
We can also speed up Workflows a bit by not needing to install `apt` packages both in the Workflow _and_ inside the docker container.

Add argument to pass in CMake command

---

README.md
action.yml
review.py

Add `base_dir` argument to more accurately fix absolute paths

---

requirements.txt
review.py

Closes #4 
Uses the `--export-fixes` argument to read in a yaml file of fixes, which are more easily turned into github suggestions.

Suggest fixits

---

README.md

Having a `.clang-tidy` file at the root of the repo is standard practice - ideally it would be [supported out of the box](https://github.com/ZedThree/clang-tidy-review/issues/29), but failing that also providing an easy copy/pasteable way to set it up would be good.

Add an example of a config_file invocation

---

review.py

I removed the raise mentioned in #39
The amazing thing is: Now the action out of the box displays `clang-diagnostic-*` warnings! I am surprised, but it's just as it should be now 🥳
here you can see a test PR with my fork that caused a compile error that was however properly posted by clang-tidy-review afterwards:
https://github.com/FlorianReimold/ecal/pull/12
_I have not tested for side-effects. Not sure if that `raise` had any important role_

Removed raise in case of clang-tidy error

---

review.py

Fixed handling of relative paths. If clang-tidy returns a relative path, it means that it is relative to the build dir, but clang-tidy-review interpreted it as being relative to the current working directory, which is the git checkout dir.
This is fixed, now, by always interpreting relative paths as relative to the build directory and converting them to absolute paths.
Fixes #41

Fixed handling of relative paths

---

README.md
action.yml
review.py

Add option to edit LGTM message and to turn it off

---

action.yml

Currently, the `--max-comments` arg only gets passed to Docker with the split workflow; with the non-split workflow, the `max_comments` action input is effectively ignored.

Pass `--max-comments` to Docker with non-split workflow too

---

post/clang_tidy_review/__init__.py

I tried something to fix #64 (not a Python expert here), I hope this works and is sufficient 🤗 .

Read from GITHUB_API_URL to work on GHES as well

---

post/clang_tidy_review/__init__.py

The `clang-tidy` output can sometimes output sorta-relative replacement FilePaths (with `..` and `.` as path components), which leads to a `KeyError`:
```
Traceback (most recent call last):
File "/action/review.py", line 205, in <module>
main(
File "/action/review.py", line 46, in main
review = create_review(
File "/action/post/clang_tidy_review/__init__.py", line 673, in create_review
review = create_review_file(
File "/action/post/clang_tidy_review/__init__.py", line 568, in create_review_file
comment_body, end_line = make_comment_from_diagnostic(
File "/action/post/clang_tidy_review/__init__.py", line 532, in make_comment_from_diagnostic
code_blocks, end_line = format_diff_line(
File "/action/post/clang_tidy_review/__init__.py", line 428, in format_diff_line
old_line, new_line = …
```

Convert all replacement FilePaths to absolute paths in `collate_replacement_sets()`

---

README.md
post/action.yml
post/clang_tidy_review/clang_tidy_review/__init__.py
post/clang_tidy_review/clang_tidy_review/post.py
tests/test_review.py
upload/action.yml

Adds a few small features:
- Try to automatically find a `.clang-tidy` file
- Make `--config_file` work with clang-tidy < 12
- Hide long notes in a collapsible section
- Add `upload` action to make uploading files a bit easier
- Automatically download artefacts from `review` Action in `post` Action
Closes #29
Closes #42 
Closes #55 
Closes #59 
Closes #61

Automatically find `.clang-tidy`; add collapsible section for notes; automatically download artefacts

---

README.md
action.yml
post/action.yml
post/clang_tidy_review/clang_tidy_review/__init__.py
post/clang_tidy_review/clang_tidy_review/post.py
post/clang_tidy_review/clang_tidy_review/review.py

Closes #51 
This is a pretty rough and ready implementation. Annotations don't support markdown, so they don't look great as I've just converted the comments straight to annotations. Using a different formatter might make them look nicer.
Also, the column isn't reported, but that could be solved with a different formatter.
Currently, if there are any issues, the status is set to `neutral`, but maybe it should be `failed`, or have a user setting to choose which one (`error_on_warnings`?).
I'm going to release this in v0.12 now, as I won't have much time to improve this for a while. PRs to make this feature better are more than welcome!

Add experimental support for annotations

---

Dockerfile

It seems that GitHub doesn't copy the git directory into the runner
Fixes #72

Don't copy .git directory into image

---

post/action.yml
post/clang_tidy_review/clang_tidy_review/post.py

Fixes #82
For some reason the event payload (sometimes?) has an empty array of `pull_requests`, but due to the way the Action is set up this passes an empty string to the input `pr_number`. This  causes an error when trying to convert to `int` to compare to the PR number in the metadata.

Always use PR number for split post workflow from uploaded metadata

---

post/clang_tidy_review/clang_tidy_review/review.py

When attempting to install packages that don't exist, the `apt-get install` invocation would exit with an error, but the script would continue. This isn't the desired behavior - the action should stop with an error.
This PR fixes that.

Check exit-code of `apt` invocations

---

post/clang_tidy_review/pyproject.toml

Relevant github discussion: https://github.com/yaml/pyyaml/issues/601
An example of build failure: https://github.com/vgvassilev/clad/actions/runs/5629104148/job/15253694275

Upgrade pyyaml to 6.0.1 to fix docker build

---

post/clang_tidy_review/clang_tidy_review/review.py

Allows to set up the workflow to fail during the review stage instead of posting stage if there are comments.

Set total_comments output if split_workflow is true

---

post/clang_tidy_review/clang_tidy_review/__init__.py
post/clang_tidy_review/pyproject.toml

Since 1.58 of PyGithub, it is required to set the base_url to the address of a github entreprise for it to work.
The version lock is loose enough that today it picks up 1.59 which requires this.

Add base_url param to github object creation

---

Dockerfile
README.md
action.yml

Switch to ubuntu lunar.
Versions 11 and 12 are not available.
In this version, installing pip packages outside of a venv are disabled by default.
Fixes  #88

Add clang-tidy 16

---

post/clang_tidy_review/clang_tidy_review/__init__.py
tests/test_review.py

There's an issue when trying to run clang-tidy without `--checks` and `--config-file`.
This is the case when you want to use the `.clang-tidy` configs in a recursive per-directory way.
In #96, I added the ability to set both checks and config to empty strings which did this, however, switching to `shell=False`, means that empty strings still count as arguments.
This ends up with `''` being sent to clang-tidy as an agument which clang-tidy interprets as a file name (`$PWD + ''` to check. It then emits and error that the current directory cannot be opened.
This PR makes sure that in this case, the `''` argument is not set and prints a more useful message in that case.

Fix Recursive source clang-tidy

---

post/clang_tidy_review/pyproject.toml

This fixes issues on build servers who have ~/.netrc that interfere with token authentication.
Prior versions would silently ignore the token and use what is in netrc instead. This was fixed in [2.1](https://github.com/PyGithub/PyGithub/releases#reactions--reaction_button_component-63ef49)

Bump PyGithub to 2.1

---

post/clang_tidy_review/clang_tidy_review/__init__.py

Improves the recommendation for `google-readability-todo` by providing a proper name which would previously be `TODO(docker)` or `TODO(unknown)`.
If for whatever reason, the name cannot be found, it will default to `TODO(your name here)`.
Closes #102 without the need for a new parameter.
Note that I think using `env` in subprocess also kill all env leaking into the call for `subprocess.run`. Hopefully no one relies on that.

Get username from PR to use in `google-readability-todo`

---

post/clang_tidy_review/clang_tidy_review/__init__.py

There is an edge case in split workflow where the `review` does not create
a `clang-tidy-review-output.json` but the rest of the workflow expects the
file to be created even if there are no comments.
This causes `cp` or `mv` operations to fail and the `post` portion of the
workflow fails trying to open an expected file.
This change makes sure the output is created even if there is nothing to
report. The body also serves to debug why there are no comments.

Fix split workflow when no comments can be posted

---

post/clang_tidy_review/clang_tidy_review/__init__.py

Setting `{"USER": username}` as env causes custom env values to be hidden.
This is an issue when using `PATH` to locate clang-tidy

Don't override original env variables

---

post/clang_tidy_review/clang_tidy_review/post.py

The default value was left a string when they were converted to `pathlib.Path` this causes a `AttributeError: 'str' object has no attribute 'exists'`

Fix default `REVIEW_FILES` in split workflow post

---

post/clang_tidy_review/clang_tidy_review/__init__.py
post/clang_tidy_review/pyproject.toml

Clean-up custom url creation and use PyGithub objects for that.
Use PyGithub checker function to catch 400+ codes.
This fixes app authenticated sessions losing the authentication for requests when downloading diffs and posting reviews.
This fixes `~/.netrc` authentication hijacking the authentication through the requests library.
Re-use the hashable comment class to filter already posted comments

Use PyGithub to reuse auth headers to do requests

---

post/clang_tidy_review/clang_tidy_review/__init__.py

40e754e removed `PullRequest.headers(type)` which breaks the artifact download:
```
Traceback (most recent call last):
File "/usr/local/bin/post", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/local/lib/python3.12/site-packages/clang_tidy_review/post.py", line 80, in main
metadata, review = download_artifacts(pull_request, int(args.workflow_id))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/clang_tidy_review/__init__.py", line 929, in download_artifacts
"GET", artifact.archive_download_url, headers=pull.headers("json")
^^^^^^^^^^^^
AttributeError: 'PullRequest' object has no attribute 'headers'
```
This refactors the download into a method on `PullRequest` which gets the appropriate headers.

fix: artifact download

---

post/clang_tidy_review/clang_tidy_review/__init__.py
post/clang_tidy_review/pyproject.toml
upload/action.yml

I'm sorry for not testing properly in https://github.com/ZedThree/clang-tidy-review/pull/115. The stuff still fails, because pygithub doesn't follow redirects and the artifact is a binary blob, not JSON (I tested it this time).
https://github.com/ZedThree/clang-tidy-review/pull/113 noted that using `requests` isn't nice, so I'm using `urllib3`.
The `accept` header might look weird, but [the documentation recommends this](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#download-an-artifact) even though we get a zip returned 🙃.
I've also noticed that this action still uses `actions/upload-action@v3` (uses deprecated node version), so I updated it to v4.
While testing, I noticed that the action fails even though it succeeded, because since …

fix: download artifacts as binary blobs and follow redirects

---

README.md
post/action.yml
post/clang_tidy_review/clang_tidy_review/post.py

I mentioned this in #118 a bit. Having the exit-code be non-zero will cause the workflow to count as failed, even though it posted the comments successfully, which will notify the user. Using `continue-on-error` isn't ideal for this either, as it will hide errors in this action. On the other hand, I can understand the use-case for this.
I'm adding the `num_comments_as_exitcode` input/option, which, as the name suggests, controls whether the exit-code will be set to the number of comments or 0. It's enabled by default, so nothing should change.

chore: add `num_comments_as_exitcode` option

---

post/clang_tidy_review/clang_tidy_review/__init__.py
tests/test_review.py

This PR attemps to give links to the review message so one can easily go read the documentation of the warning in question.
> warning: missing username/bug in TODO [google-readability-todo]
> 
> ```suggestion
> // TODO(bwrsandman): Cause a clang-tidy error
> ```
Should now look like
> warning: missing username/bug in TODO [[google-readability-todo](https://clang.llvm.org/extra/clang-tidy/checks/google/readability-todo.html)]
> 
> ```suggestion
> // TODO(bwrsandman): Cause a clang-tidy error
> ```
Proof of concept:

Add links to check documentation in review

---

Dockerfile
README.md
action.yml

Since Ubuntu 24.04 LTS is now available, this adds support for versions 17 and 18 (the latter becoming the default).
It also removes version 13 as it's no longer available in Ubuntu Noble's repos.

Add clang-tidy 18

---

post/clang_tidy_review/clang_tidy_review/__init__.py

ensure diff paths are the same on all platforms

---

post/clang_tidy_review/clang_tidy_review/__init__.py

The decoration function changes the review comment text so it must be done before culling

Fix regression to cull_comments

---

post/clang_tidy_review/clang_tidy_review/__init__.py

When opening a PR without any changes (with one or more empty commits), `clang-tidy-review` currently fails with
```
Traceback (most recent call last):
File "/usr/local/bin/review", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/local/lib/python3.12/dist-packages/clang_tidy_review/review.py", line 154, in main
review = create_review(
^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/clang_tidy_review/__init__.py", line 843, in create_review
diff = pull_request.get_pr_diff()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/clang_tidy_review/__init__.py", line 297, in get_pr_diff
diffs = data["data"]
~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
This PR checks `data` and returns with no changes.
While doing that, I noticed the …

fix: support empty commits/PRs

---

action.yml
post/clang_tidy_review/clang_tidy_review/__init__.py
post/clang_tidy_review/clang_tidy_review/review.py
tests/test_review.py

This PR streamlines `build_clang_tidy_warnings` to be easily dispatched by a multi-process queue. Each process stores the fixes in a temporary directory.
The queue will dispatch a clang-tidy process per file to check. This way more complex files can run at the same time as less complex ones.
Added a function to combine fixes after the queue is done running.
The design is copied from llvm's `run-clang-tidy.py` script and adapted for the current code.
Things I've noticed running this:
* On ubuntu actions, this spawns 4 processes.
* ~~Cancelling a workflow only cancels the running queue processes but will still do the post step.~~
* The logs get spammed. (#128)
* It's hard to tell which log did what.
* A change with 28 files took 17m 45s with 4 processes while upstream took 33m 11s
* The …

Use task queue to spawn multiple processes of tidy

---

post/clang_tidy_review/clang_tidy_review/__init__.py
post/clang_tidy_review/clang_tidy_review/post.py
post/clang_tidy_review/clang_tidy_review/review.py

As the title says, this fixes the remaining lints from https://github.com/ZedThree/clang-tidy-review/pull/133 (that's the target of the PR) as well as some typing errors (the remaining ones can be fixed in a separate PR). I noticed that `pygithub` now has [`PullRequest.get_comments`](https://pygithub.readthedocs.io/en/stable/github_objects/PullRequest.html#github.PullRequest.PullRequest.get_comments) which we could migrate to. Furthermore, there should probably a ruff check in CI.
Aside: A release would be great. Currently, comments are duplicated (not culled) - this is fixed on master (I think).

Fix remaining Ruff lints and (most) type errors

---

post/clang_tidy_review/clang_tidy_review/__init__.py
tests/test_review.py

Since the review files are `Path`s now, they can't be searched by in `list[str]`s. In particular, the file can't be searched in `ZipFile#namelist()` in `download_artifacts` (example run: https://github.com/Chatterino/chatterino2/actions/runs/11756776343/job/32753285579).
This PR, in particular the first commit, fixes that by converting to a string.
With paths being `Path`s now, many `Path(foo)` can be converted to `foo`. The tests didn't pass `Path`s, so I fixed that too.
I tested the last commit at https://github.com/Nerixyz/test-mini-cpp-project/pull/6.

fix(split-review): search by string in names

---

post/clang_tidy_review/clang_tidy_review/__init__.py
post/clang_tidy_review/pyproject.toml

When trying to post comments to a PR which already has review comments, the action currently fails ([example](https://github.com/Nerixyz/test-mini-cpp-project/actions/runs/13549744175/job/37870205707)).
Pygithub 2.6.0 updated the `PullRequestComment` class and added the remaining fields we needed, so it should be easier to use `PullRequestComment` directly.
I tested this in https://github.com/Nerixyz/test-mini-cpp-project/pull/10 where I had some additional debug logging for the comments.
One thing I was confused about was that `line`  returns `None` for some review comments. However, `original_line` seems to be populated in that case.

fix: use pygithub to get PR comments

---

README.md
action.yml
post/clang_tidy_review/clang_tidy_review/review.py

sometimes just running apt-get install is not enough, so allow providing arbitrary installation commands
[note] I am aware that the commands can (currently) just be added to `cmake_command` but I do find that a bit ugly.

[install_commands] add option to inject install commands
